import os
import sys
import argparse
import logging
import scripts
from scripts import module
from datetime import datetime
from pathlib import Path
from glob import glob
from concurrent.futures import ProcessPoolExecutor, as_completed

def fetch_arguments(parser,root_dir,db_path_default):
    parser.set_defaults(func=main)
    parser.set_defaults(program="run")
    parser.add_argument('--input_metagenome','-i', dest='input_metagenome', required=True, default='none', help=r'(required) input metagenome assembly. It can be a metagenome or entire virome assembly. The extension of the input nucleotide sequence should be ".fasta"')
    parser.add_argument('--input_reads', '-r', dest = 'input_reads', required=False, default='none', help=r'(required) input metagenomic reads. The input paired reads should be  "forward_1.fastq or forward_R1.fastq" and "reverse_2.fastq or reverse_R2.fastq" connected by ",". Multiple paired reads can be provided at the same time for one metagenome assembly, connected by ",".  For example: -r /path/to/Lake_01_T1_1.fastq,/path/to/Lake_01_T1_2.fastq,/path/to/Lake_01_T2_1.fastq,/path/to/Lake_01_T2_2.fastq  Note that the extension of the input reads should be ".fastq" or ".fastq.gz"')
    parser.add_argument('--input_reads_type', '-rt', dest = 'input_reads_type', required=False, default='illumina', help=r'input metagenomic reads type. The default is illumina. If you are using long reads, you will need to assign: pacbio - PacBio CLR reads, pacbio_hifi - PacBio HiFi/CCS reads, pacbio_asm20 - PacBio HiFi/CCS reads asm20, nanopore - Oxford Nanopore reads')
    parser.add_argument('--input_cov', '-cov', dest = 'input_cov', required=False, default='none', help=r'input coverage file. When this option is used, --input_reads should not be used. This option will intake a pre-made coverage file that was generated by short reads metagenomic mapping')
    parser.add_argument('--input_sample2read_info', dest = 'input_sample2read_info', required=False, default='none', help=r'input sample2read_info file. When this option is used, --input_reads should not be used. This option will intake a pre-made sample2read_info file that was generated by short reads fastq files')
    parser.add_argument('--reads_mapping_identity_cutoff', '-id', dest = 'reads_mapping_identity_cutoff', required=False, default=0.97, help=r'reads mapping identity cutoff. The default is 0.97. 0.97 is suitable for all illumina reads and also suitable for PacBio Sequel II or Nanopore PromethION Q20+ reads. For other PacBio or Nanopore reads with high error rate, the id cutoff is suggested to be 1 - error rate')
    parser.add_argument('--skip_long_reads_correction', dest='skip_long_reads_correction', action='store_true', required=False, default=False, help=r"when using long reads that have been corrected by CONSENT, use this option to skip long reads correction")
    parser.add_argument('--out_dir','-o', dest='out_dir', required=False, default='./ViWrap_outdir', help=r'(required) output directory to deposit all results (default = ./ViWrap_outdir) output folder to deposit all results. ViWrap will exit if the folder already exists')
    parser.add_argument('--db_dir','-d', dest='db_dir', required=False, default=db_path_default, help=f'(required) database directory; default = {db_path_default}')
    parser.add_argument('--identify_method', dest='identify_method', required=False, default='genomad',help=r'(required) the virus identifying method to choose: vb - VIBRANT; vs - VirSorter2 and CheckV; dvf - DeepVirFinder; vb-vs - Use VIBRANT and VirSorter2 to get the overlapped viruses (default); vb-vs-dvf - Use all these three methods and get the overlapped viruses; genomad - Use geNomad')
    parser.add_argument('--conda_env_dir', dest='conda_env_dir', required=True, default='none', help=r'(required) the directory where you put your conda environment files. It is the parent directory that contains all the conda environment folders')
    parser.add_argument('--threads','-t', dest='threads', required=False, default=10, help=r'number of threads (default = 10)')
    parser.add_argument('--virome','-v', dest='virome', action='store_true', required=False, default=False, help=r"edit VIBRANT's sensitivity if the input dataset is a virome. It is suggested to use it if you know that the input assembly is virome or metagenome")
    parser.add_argument('--input_length_limit', dest='input_length_limit', required=False, default=2000, help=r'length in basepairs to limit input sequences (default=2000, can increase but not decrease); 2000 at least suggested for VIBRANT (vb)-based pipeline, 5000 at least suggested for VirSorter2 (vs)-based pipeline')
    parser.add_argument('--custom_MAGs_dir', dest='custom_MAGs_dir', required=False, default='none', help=r'custom MAGs dir that contains only *.fasta files for MAGs reconstructed from the same metagenome, this will be used in iPHoP for host prediction; note that it should be the absolute address path')	
    parser.add_argument('--iPHoP_db_custom', dest='iPHoP_db_custom', required=False, default='none', help=r'custom iPHoP db that will be generated by your input custom MAGs; note that it should be the absolute address path')	
    parser.add_argument('--iPHoP_db_custom_pre', dest='iPHoP_db_custom_pre', required=False, default='none', help=r'custom iPHoP db that has been made from the previous run, this will be used in iPHoP for host prediction by custom db; note that it should be the absolute address path')
    parser.add_argument('--root_dir', dest='root_dir', required=False, default=root_dir,help=argparse.SUPPRESS)
    

def set_defaults(args):
    ## Store databases
    args['CheckV_db'] = os.path.join(args['db_dir'],'CheckV_db')
    args['DRAM_db'] = os.path.join(args['db_dir'],'DRAM_db')
    args['GTDB_db'] = os.path.join(args['db_dir'],'GTDB_db')
    args['iPHoP_db'] = os.path.join(args['db_dir'],'iPHoP_db')
    args['Kofam_db'] = os.path.join(args['db_dir'],'Kofam_db')
    args['Tax_classification_db'] = os.path.join(args['db_dir'],'Tax_classification_db')
    args['VIBRANT_db'] = os.path.join(args['db_dir'],'VIBRANT_db')
    args['VirSorter2_db'] = os.path.join(args['db_dir'],'VirSorter2_db')
    args['DVF_db'] = os.path.join(args['db_dir'],'DVF_db')
    args['geNomad_db'] = os.path.join(args['db_dir'],'genomad_db')
    
    ## Store outdirs 
    args['vibrant_outdir'] = os.path.join(args['out_dir'],f"00_VIBRANT_{Path(args['input_metagenome']).stem}")
    args['virsorter_outdir'] = os.path.join(args['out_dir'],f"00_VirSorter_{Path(args['input_metagenome']).stem}")
    args['dvf_outdir'] = os.path.join(args['out_dir'],f"00_DeepVirFinder_{Path(args['input_metagenome']).stem}")
    args['vb_vs_dvf_outdir'] = os.path.join(args['out_dir'],f"00_VIBRANT_VirSorter_DeepVirFinder_{Path(args['input_metagenome']).stem}")
    args['vb_vs_outdir'] = os.path.join(args['out_dir'],f"00_VIBRANT_VirSorter_{Path(args['input_metagenome']).stem}")
    args['genomad_outdir'] = os.path.join(args['out_dir'],f"00_geNomad_{Path(args['input_metagenome']).stem}")
    args['mapping_outdir'] = os.path.join(args['out_dir'],'01_Mapping_result_outdir')
    args['vrhyme_outdir'] = os.path.join(args['out_dir'],'02_vRhyme_outdir')
    args['vcontact2_outdir'] = os.path.join(args['out_dir'],'03_vConTACT2_outdir')
    args['nlinked_viral_gn_dir'] = os.path.join(args['out_dir'],'04_Nlinked_viral_gn_dir')
    args['checkv_outdir'] = os.path.join(args['out_dir'],'05_CheckV_outdir')
    args['drep_outdir'] = os.path.join(args['out_dir'],'06_dRep_outdir')
    args['iphop_outdir'] = os.path.join(args['out_dir'],'07_iPHoP_outdir')
    args['iphop_custom_outdir'] = os.path.join(args['out_dir'],'07_iPHoP_outdir/iPHoP_outdir_custom_MAGs')
    args['viwrap_summary_outdir'] = os.path.join(args['out_dir'],'08_ViWrap_summary_outdir')
    args['viwrap_visualization_outdir'] = os.path.join(args['out_dir'],'09_Virus_statistics_visualization')

## Set up the logger
def get_logger(args):
    log_file = os.path.join(args['out_dir'],'ViWrap_run.log')
    logging.basicConfig(
        level=logging.INFO,
        format="%(message)s",
        handlers=[
            logging.FileHandler(log_file),
            logging.StreamHandler(sys.stdout)
        ]
    )    
    logger = logging.getLogger(__name__) 
    return logger

def dvf(args, output_file_surfix="dvf"):
    print("DVF starts")
    logger = get_logger(args)
    header_replaced_input_metagenome = os.path.join(args['out_dir'], f"{Path(args['input_metagenome']).stem}_{output_file_surfix}.fasta")
    scripts.module.make_short_headers_fasta(args['input_metagenome'], header_replaced_input_metagenome)    
    os.system(f"conda run -p {os.path.join(args['conda_env_dir'], 'ViWrap-DVF')} python {os.path.join(args['root_dir'],'scripts/run_DVF.py')} {header_replaced_input_metagenome} {args['dvf_outdir']} {args['input_length_limit']} {args['DVF_db']} >/dev/null 2>&1")
    os.system(f"rm {header_replaced_input_metagenome}")  
    print("DVF still works")
    final_dvf_virus_fasta_file = os.path.join(args['dvf_outdir'], 'final_dvf_virus.fasta')
    scripts.module.get_dvf_result_seq(args, args['dvf_outdir'], final_dvf_virus_fasta_file)
    
    time_current = f"[{str(datetime.now().replace(microsecond=0))}]"
    logger.info(f"{time_current} | Run DeepVirFinder to identify viruses from input metagenome. Finished")   

def genomad(args):
    print("geNomad starts")
    logger = get_logger(args)
    time_current = f"[{str(datetime.now().replace(microsecond=0))}]"
    logger.info(f"{time_current} | Run geNomad to identify and annotate viruses from input metagenome. In processing...")

    length_filtered_input_metagenome = os.path.join(args['out_dir'], f"{Path(args['input_metagenome']).stem}.fasta")
    scripts.module.filter_fasta_by_length(args['input_metagenome'], length_filtered_input_metagenome, args['input_length_limit'])
    os.system(f"conda run -p {os.path.join(args['conda_env_dir'], 'ViWrap-geNomad')} python {os.path.join(args['root_dir'],'scripts/run_geNomad.py')} {length_filtered_input_metagenome} {args['out_dir']} {args['threads']} {args['db_dir']} >/dev/null 2>&1")
    default_genomad_outdir = os.path.join(args['out_dir'], 'genomad_output')
    os.system(f"mv {default_genomad_outdir} {args['genomad_outdir']}; rm {length_filtered_input_metagenome}")
    scripts.module.parse_genomad_lytic_and_lysogenic_info(args['genomad_outdir'], Path(args['input_metagenome']).stem)
    # Copy resulted fna and faa files
    genomad_virus_fna = f"{args['genomad_outdir']}/{Path(args['input_metagenome']).stem}_summary/{Path(args['input_metagenome']).stem}_virus.fna"
    genomad_virus_faa = f"{args['genomad_outdir']}/{Path(args['input_metagenome']).stem}_summary/{Path(args['input_metagenome']).stem}_virus_proteins.faa"
    os.system(f"cp {genomad_virus_fna} {args['genomad_outdir']}/final_genomad_virus.fasta; cp {genomad_virus_faa} {args['genomad_outdir']}/final_genomad_virus.faa")
    print("geNomad ends")

def vb(args, output_file_surfix="vb"):
    print("vb start!")
    logger = get_logger(args)
    time_current = f"[{str(datetime.now().replace(microsecond=0))}]"
    logger.info(f"{time_current} | Run VIBRANT to identify and annotate viruses from input metagenome. In processing...")
    
    # change surfix with "vb" added
    header_replaced_input_metagenome = os.path.join(args['out_dir'], f"{Path(args['input_metagenome']).stem}_{output_file_surfix}.fasta")
    scripts.module.make_short_headers_fasta(args['input_metagenome'], header_replaced_input_metagenome)              
    os.system(f"conda run -p {os.path.join(args['conda_env_dir'], 'ViWrap-VIBRANT')} python {os.path.join(args['root_dir'],'scripts/run_VIBRANT.py')} {header_replaced_input_metagenome} {args['out_dir']} {args['threads']} {args['virome']} {args['input_length_limit']} {args['db_dir']} >/dev/null 2>&1")
    default_vibrant_outdir = os.path.join(args['out_dir'],f"VIBRANT_{Path(args['input_metagenome']).stem}_{output_file_surfix}")
    os.system(f"mv {default_vibrant_outdir} {args['vibrant_outdir']}; rm {header_replaced_input_metagenome}")
    scripts.module.parse_vibrant_lytic_and_lysogenic_info(args['vibrant_outdir'], f"{Path(args['input_metagenome']).stem}_{output_file_surfix}")

    time_current = f"[{str(datetime.now().replace(microsecond=0))}]"
    logger.info(f"{time_current} | Run VIBRANT to identify and annotate viruses from input metagenome. Finished")

def vs(args, output_file_surfix="vs"):
    
    logger = get_logger(args)
    time_current = f"[{str(datetime.now().replace(microsecond=0))}]"
    logger.info(f"{time_current} | Run VirSorter2 to identify viruses from input metagenome. Also plus CheckV to QC and trim, and KEGG, Pfam, and VOG HMMs to annotate viruses. In processing...")    

    # change surfix with "vs" added
    header_replaced_input_metagenome = os.path.join(args['out_dir'], f"{Path(args['input_metagenome']).stem}_{output_file_surfix}.fasta")
    scripts.module.make_short_headers_fasta(args['input_metagenome'], header_replaced_input_metagenome)      
    print("vs conda begins")
    os.system(f"conda run -p {os.path.join(args['conda_env_dir'], 'ViWrap-vs2')} python {os.path.join(args['root_dir'],'scripts/run_VirSorter2.py')} {header_replaced_input_metagenome} {args['virsorter_outdir']} {args['threads']} {args['input_length_limit']}")
    print("vs conda ends.")
    os.system(f"rm {header_replaced_input_metagenome}")  
    time_current = f"[{str(datetime.now().replace(microsecond=0))}]"
    logger.info(f"{time_current} | Run VirSorter2 to identify viruses from input metagenome. Finished")    

    os.system(f"conda run -p {os.path.join(args['conda_env_dir'], 'ViWrap-CheckV')} python {os.path.join(args['root_dir'],'scripts/run_VirSorter2_CheckV.py')} {args['virsorter_outdir']} {args['threads']} {args['CheckV_db']}")
    
    time_current = f"[{str(datetime.now().replace(microsecond=0))}]"
    logger.info(f"{time_current} | Run CheckV to QC and trim viruses identified from VirSorter2. Finished")   

    keep1_list_file = os.path.join(args['virsorter_outdir'], 'keep1_list.txt')
    keep2_list_file = os.path.join(args['virsorter_outdir'], 'keep2_list.txt')
    discard_list_file = os.path.join(args['virsorter_outdir'], 'discard_list.txt')
    manual_check_list_file = os.path.join(args['virsorter_outdir'], 'manual_check_list.txt')
    scripts.module.screen_virsorter2_result(args['virsorter_outdir'], keep1_list_file, keep2_list_file, discard_list_file, manual_check_list_file)
    
    keep2_fasta = os.path.join(args['virsorter_outdir'], 'keep2.fasta')
    manual_check_fasta = os.path.join(args['virsorter_outdir'], 'manual_check.fasta')
    scripts.module.get_keep2_mc_seq(args['virsorter_outdir'], keep2_list_file, manual_check_list_file, keep2_fasta, manual_check_fasta)
    
    if os.path.exists(keep2_fasta) and os.path.getsize(keep2_fasta) != 0:
        os.system(f"conda run -p {os.path.join(args['conda_env_dir'], 'ViWrap-VIBRANT')} python {os.path.join(args['root_dir'],'scripts/run_VIBRANT.py')} {keep2_fasta} {args['virsorter_outdir']} {args['threads']} {args['virome']} {args['input_length_limit']} {args['db_dir']} >/dev/null 2>&1")
        keep2_vb_result = os.path.join(args['virsorter_outdir'], 'VIBRANT_keep2/VIBRANT_phages_keep2/keep2.phages_combined.fna') 
        keep2_list_vb_passed_file = os.path.join(args['virsorter_outdir'], 'keep2_list_vb_passed.txt')
        scripts.module.get_keep2_vb_passed_list(args['virsorter_outdir'], keep2_vb_result, keep2_list_vb_passed_file)
        os.system(f"rm -r {os.path.join(args['virsorter_outdir'], 'VIBRANT_keep2')}")
    if os.path.exists(manual_check_fasta) and os.path.getsize(manual_check_fasta) != 0:
        os.system(f"conda run -p {os.path.join(args['conda_env_dir'], 'ViWrap-VIBRANT')} python {os.path.join(args['root_dir'],'scripts/run_VIBRANT.py')} {manual_check_fasta} {args['virsorter_outdir']} {args['threads']} {args['virome']} {args['input_length_limit']} {args['db_dir']} >/dev/null 2>&1")
        manual_check_vb_result = os.path.join(args['virsorter_outdir'], 'VIBRANT_manual_check/VIBRANT_phages_manual_check/manual_check.phages_combined.fna') 
        manual_check_list_vb_passed_file = os.path.join(args['virsorter_outdir'], 'manual_check_list_vb_passed.txt')
        scripts.module.get_manual_check_vb_passed_list(args['virsorter_outdir'], manual_check_vb_result, manual_check_list_vb_passed_file)
        os.system(f"rm -r {os.path.join(args['virsorter_outdir'], 'VIBRANT_manual_check')}")            

    keep2_list_vb_passed_file = os.path.join(args['virsorter_outdir'], 'keep2_list_vb_passed.txt')
    manual_check_list_vb_passed_file = os.path.join(args['virsorter_outdir'], 'manual_check_list_vb_passed.txt')
    final_vs2_virus_fasta_file = os.path.join(args['virsorter_outdir'], 'final_vs2_virus.fasta')
    scripts.module.get_final_vs2_virus(args['virsorter_outdir'], keep1_list_file, keep2_list_vb_passed_file, manual_check_list_vb_passed_file, final_vs2_virus_fasta_file)
    
    time_current = f"[{str(datetime.now().replace(microsecond=0))}]"
    logger.info(f"{time_current} | Run VIBRANT to check \"keep2\" and \"manual_check\" groups and get the final VirSorter2 virus sequences. Finished")  


def main(args):
    # Welcome and logger
    print("### Welcome to ViWrap ###\n") 

    # Check if the output directory already exists
    if os.path.exists(args['out_dir']):
        sys.exit(f"Error: The output directory '{args['out_dir']}' already exists. Please specify a different directory or remove the existing one.")
    else:
        # Create the output directory since it does not exist
        os.mkdir(args['out_dir'])
    
    logger_main =get_logger(args)
    logger_vb = get_logger(args)
    logger_vs = get_logger(args)

    ## Store the input arguments
    issued_command = scripts.module.get_run_input_arguments(args)
    logger_main.info(f"The issued command is:\n{issued_command}\n")
    
    ## Set the default args:
    set_defaults(args)
    
    # Step 1 Pre-check inputs
    start_time = datetime.now().replace(microsecond=0)
    time_current = f"[{str(datetime.now().replace(microsecond=0))}]"
    logger_main.info(f"{time_current} | Pre-check inputings. In processing...")
    
    if not os.path.exists(args['input_metagenome']):
        sys.exit(f"Could not find input metagenome {args['input_metagenome']}")        
    if not os.path.exists(args['db_dir']):
        sys.exit(f"Could not find directory {args['db_dir']}. Maybe the database directory was not specified with the --db_dir and is not the default \".ViWrap_db/\" directory?")

    if args['input_reads_type'] != 'illumina' and args['input_reads_type'] != 'pacbio' and args['input_reads_type'] != 'pacbio_hifi' and args['input_reads_type'] != 'pacbio_asm20' and args['input_reads_type'] != 'nanopore':
        sys.exit(f"The input reads type should be one of these: illumina, pacbio, pacbio_hifi, pacbio_asm20, and nanopore")  
        
    # Give requirements for the usage of options "input_reads"
    sample2read_info = {}
    if args['input_reads'] != 'none' and args['input_cov'] == 'none' and args['input_sample2read_info'] == 'none':
        metaG_reads_list = args['input_reads'].split(',')
        for each_read in metaG_reads_list:
            if not each_read.endswith('.fastq') and not each_read.endswith('.fastq.gz'):
                sys.exit(f"Please make sure that all your input reads are ended with .fastq or fastq.gz")  
    
        sample2read_info = scripts.module.get_read_info(args['input_reads'], args['input_reads_type']) 
    # Give requirements for the usage of options "input_cov" and "input_sample2read_info"
    elif args['input_reads'] == 'none' and (args['input_cov'] != 'none' and args['input_sample2read_info'] != 'none'):       
        sample2read_info = scripts.module.get_input_read_info(args['input_sample2read_info']) 
    elif args['input_reads'] != 'none' and (args['input_cov'] != 'none' or args['input_sample2read_info'] != 'none'):
        sys.exit(f"Please make sure that --input_reads can not be used together with --input_cov and --input_sample2read_info")
    elif args['input_reads'] == 'none' and not (args['input_cov'] != 'none' and args['input_sample2read_info'] != 'none'):
        sys.exit(f"Please make sure that --input_cov and --input_sample2read_info should be used together")
    
    # Give requirements for the usage of options "custom_MAGs_dir" and "iPHoP_db_custom"
    if args['custom_MAGs_dir'] != 'none' and not os.path.exists(args['custom_MAGs_dir']):
        sys.exit(f"Could not find custom MAGs directory {args['custom_MAGs_dir']}. Maybe the directory is not correct")
    elif args['custom_MAGs_dir'] != 'none' and not os.path.isabs(args['custom_MAGs_dir']):
        sys.exit(f"The input custom MAGs directory {args['custom_MAGs_dir']} is not an absolute address, please change it to an absolute address")
    elif args['custom_MAGs_dir'] != 'none' and os.path.exists(args['custom_MAGs_dir']):   
        for file in glob(os.path.join(args['custom_MAGs_dir'],'*.fasta')):
            if '.fasta' not in file:
                sys.exit(f"Make sure all MAGs in custom MAGs directory {args['custom_MAGs_dir']} end with \'.fasta\', and no additional files within the directory")
        if args['iPHoP_db_custom'] == 'none':
            sys.exit(f"Make sure you have assigned a proper address to iPHoP_db_custom by using the option '--iPHoP_db_custom'")
        elif args['iPHoP_db_custom'] != 'none' and os.path.exists(args['iPHoP_db_custom']):
            sys.exit(f"Please make sure that {args['iPHoP_db_custom']} is not present before ViWrap run. If present, please remove the folder. If you want to use the iPHoP_db_custom generated by your previous run, please use '--iPHoP_db_custom_pre' instead") 
        elif args['iPHoP_db_custom'] != 'none' and not os.path.exists(args['iPHoP_db_custom']) and not os.path.isabs(args['iPHoP_db_custom']):  
            sys.exit(f"Please make sure that {args['iPHoP_db_custom']} is an absolute address") 
        
    # Give requirements for the usage of the option of "iPHoP_db_custom_pre"
    if args['iPHoP_db_custom_pre'] != 'none':
        if not os.path.exists(args['iPHoP_db_custom_pre']):
            sys.exit(f"Could not find 'iPHoP_db_custom_pre' directory {args['iPHoP_db_custom_pre']}. Maybe the directory is not correct")
        elif os.path.exists(args['iPHoP_db_custom_pre']) and not os.path.isabs(args['iPHoP_db_custom_pre']):
            sys.exit(f"The input 'iPHoP_db_custom_pre' directory {args['iPHoP_db_custom_pre']} is not an absolute address, please change it to an absolute address")
        elif args['custom_MAGs_dir'] != 'none' or args['iPHoP_db_custom'] != 'none':
            sys.exit(f"If you use --iPHoP_db_custom_pre, you should not use --custom_MAGs_dir or --iPHoP_db_custom. Simply assign the custom iPHoP db that has been made from the previous run")
           
    if not os.path.exists(args['conda_env_dir']):
        sys.exit(f"Could not find conda env dirs within {args['conda_env_dir']}") 
        
    if int(args['input_length_limit']) < 2000 and 'vs' in args['identify_method']:
        sys.exit(f"Since you have included vs - VirSorter2 in the identify_method, you have to use input_length_limit that >= 2000") 
     
    time_current = f"[{str(datetime.now().replace(microsecond=0))}]"
    logger_main.info(f"{time_current} | Looks like the input metagenome and reads, database, and custom MAGs dir (if option used) are now set up well, start up to run ViWrap pipeline")
    
    # run vb, vs parallelly
    
    with ProcessPoolExecutor(max_workers=2) as executor:
        futures = [
            executor.submit(vb, args),   # 第一个任务
            executor.submit(vs, args),    # 第二个任务
            executor.submit(dvf, args),   # 第三个任务
            executor.submit(genomad, args) # 第四个任务
        ]

        for future in as_completed(futures):
            try:
                result = future.result()
                print(result)
            except Exception as e:
                print(f"任务出错：{e}")

    